### ISSUE TITLE
Issues with golang 1.13 and windows 10 x64

### ISSUE THREAD

**Issue by Haslonse** [pantos-io/go-testimonium#2]
Seems like I can't 'get' it with golang 1.13 on Win10x64. Installed 1.12rc1 and testing it now, but seems more promising. Which exact version was used? I am new to golang and would like some more instructions in the readme for the first steps.  Thanks in Advance!

Update: 1.12rc1 didn't work either. Probably Windows related stuff, so I stopped bothering. I switched to WSL with Debian for now. Hope I can get it running now. (I know I should have used linux in the first place haha)

**Update 2** Everything works now with Windows Subsystem for Linux and Debian.

**Comment by msigwart** [comment]
Thanks for the issue! We tested with golang 1.12. I will close the issue for now since it seems that you got it working :)
